### ISSUE TITLE
Dependency on pip

### ISSUE THREAD

**Issue by jayvdb** [sirosen/callable-pip#1]
This package needs a dependency on `pip`, at least for versions of Python 2 before `ensurepip`.

And it should internally run `ensurepip` if `pip` is missing.

And running some tests would be useful ;-)

**Comment by sirosen** [comment]
I disagree on two of these points. The point of this package was to offer a way to call `pip` from within an interpreter, and secondarily to offer mechanisms to patch that into place for programs which relied on `pip.main`.
Invoking `ensurepip` and having a packaging dependency on `pip` are out of scope and have undesirable side-effects, respectively.

It would be nice to have some tests written, but since I don't intend to pick the project back up, I don't see much point in adding any.
